In [1]:
import numpy as np
import tensorflow as tf

In [2]:
import sys
sys.path.append('../')

In [3]:
from influence.influence_model import InfluenceModel

In [4]:
# Simple Keras model for MNIST Fashion Dataset, based on TensorFlow tutorials.

fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

train_images = train_images / 255.0
test_images = test_images / 255.0

train_labels = tf.keras.utils.to_categorical(train_labels)
test_labels = tf.keras.utils.to_categorical(test_labels)

tf.keras.backend.set_floatx('float64')

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(32, activation='relu', kernel_regularizer='l2', bias_regularizer='l2'),
    tf.keras.layers.Dense(10, kernel_regularizer='l2', bias_regularizer='l2')
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=10)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 3s 43us/sample - loss: 0.9725 - accuracy: 0.7888
Epoch 2/10
60000/60000 [==============================] - 2s 37us/sample - loss: 0.8553 - accuracy: 0.8074
Epoch 3/10
60000/60000 [==============================] - 2s 38us/sample - loss: 0.8496 - accuracy: 0.8094
Epoch 4/10
60000/60000 [==============================] - 2s 38us/sample - loss: 0.8480 - accuracy: 0.8101
Epoch 5/10
60000/60000 [==============================] - 2s 37us/sample - loss: 0.8450 - accuracy: 0.8099
Epoch 6/10
60000/60000 [==============================] - 2s 37us/sample - loss: 0.8450 - accuracy: 0.8123
Epoch 7/10
60000/60000 [==============================] - 2s 37us/sample - loss: 0.8422 - accuracy: 0.8127
Epoch 8/10
60000/60000 [==============================] - 2s 37us/sample - loss: 0.8430 - accuracy: 0.8131
Epoch 9/10
60000/60000 [==============================] - 2s 37us/sample - loss: 0.8417 - accuracy: 0.8120
Epoch 10/10
60

In [5]:
influence_model = InfluenceModel(
    model,
    train_images,
    train_labels,
    model.loss,
    0,
    scaling=0.01,
    damping=0.01,
    verbose=True,
    dtype=np.float64
)

In [6]:
influence_model.get_influence_on_loss(
    test_images[0],
    test_labels[0]
)

Calculating Inverse HVP:
CG Loss:  -0.0007797994446898379 ; CG Jac Norm: 0.0030180610223686133
CG Loss:  -0.0008991900584138726 ; CG Jac Norm: 0.003755772048104661
CG Loss:  -0.0010219837227193017 ; CG Jac Norm: 0.0026108493317911533
CG Loss:  -0.0010659894623489864 ; CG Jac Norm: 0.001288176911779649
CG Loss:  -0.0010769628980666212 ; CG Jac Norm: 0.0011089086334720771
CG Loss:  -0.0010831892113772027 ; CG Jac Norm: 0.0004866932946547655
CG Loss:  -0.001086095873638684 ; CG Jac Norm: 0.00025634903186763777
CG Loss:  -0.0010864529887243991 ; CG Jac Norm: 0.00018769069004020948
CG Loss:  -0.0010869164285939505 ; CG Jac Norm: 0.00013002846294514538
CG Loss:  -0.0010871123260737768 ; CG Jac Norm: 0.0001354307918425715
CG Loss:  -0.0010872270669602265 ; CG Jac Norm: 8.6351225557117e-05
CG Loss:  -0.0010873309029095326 ; CG Jac Norm: 4.4483889622474206e-05
CG Loss:  -0.0010873415290341606 ; CG Jac Norm: 3.2251640290225354e-05
Optimization terminated successfully.
         Current function v

-0.6812242747057422

In [7]:
influence_model.get_theta_relatif(
    test_images[0],
    test_labels[0]
)

-2.0623104283367084

In [8]:
influence_model.get_l_relatif(
    test_images[0],
    test_labels[0]
)

-14.61304482241689

In [9]:
influence_model.get_new_parameters()

[<tf.Tensor: shape=(784, 32), dtype=float64, numpy=
 array([[ 1.42667164e-05, -1.79125082e-09,  1.88606055e-05, ...,
          6.78263373e-05, -1.96381059e-06, -1.02653369e-14],
        [-4.36293675e-05,  7.68579341e-05, -2.70055872e-04, ...,
          9.71025243e-05,  2.76455677e-05,  6.98906818e-13],
        [-3.27442843e-04, -9.84308724e-06,  3.28725436e-04, ...,
         -2.64829468e-04, -6.95738541e-05,  2.11315440e-06],
        ...,
        [ 1.60155204e-03, -1.11749811e-03, -2.89645152e-03, ...,
          1.33736046e-03,  2.29213283e-03,  6.50965776e-05],
        [-1.25441813e-03,  1.02509407e-04, -1.73070135e-03, ...,
          5.25938292e-03,  3.96752721e-04,  2.07130010e-05],
        [ 1.76228843e-03,  8.44158789e-05,  2.11016185e-03, ...,
          5.50023553e-03,  4.13510528e-03, -9.72172808e-08]])>,
 <tf.Tensor: shape=(32,), dtype=float64, numpy=
 array([-1.14678361e-01,  7.71840377e-02, -8.51232895e-02,  7.24886787e-02,
        -1.12965258e-01,  3.83519794e-01,  7.6596934