In [1]:
import numpy as np
import tensorflow as tf

In [2]:
import sys
sys.path.append('../')

In [3]:
from influence.influence_model import InfluenceModel

In [4]:
fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

train_images = train_images / 255.0
test_images = test_images / 255.0

train_labels = tf.keras.utils.to_categorical(train_labels)
test_labels = tf.keras.utils.to_categorical(test_labels)

tf.keras.backend.set_floatx('float64')

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(10, kernel_regularizer='l2', bias_regularizer='l2')
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 1s 711us/step - loss: 0.8448 - accuracy: 0.7835
Epoch 2/10
1875/1875 [==============================] - 1s 697us/step - loss: 0.7640 - accuracy: 0.8118
Epoch 3/10
1875/1875 [==============================] - 1s 767us/step - loss: 0.7640 - accuracy: 0.8117
Epoch 4/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.7641 - accuracy: 0.8126
Epoch 5/10
1875/1875 [==============================] - 1s 745us/step - loss: 0.7632 - accuracy: 0.8131
Epoch 6/10
1875/1875 [==============================] - 1s 752us/step - loss: 0.7625 - accuracy: 0.8142
Epoch 7/10
1875/1875 [==============================] - 1s 749us/step - loss: 0.7634 - accuracy: 0.8132
Epoch 8/10
1875/1875 [==============================] - 1s 752us/step - loss: 0.7630 - accuracy: 0.8125
Epoch 9/10
1875/1875 [==============================] - 1s 715us/step - loss: 0.7630 - accuracy: 0.8131
Epoch 10/10
1875/1875 [==============================] - 1s 729us/

In [5]:
influence_model = InfluenceModel(
    model,
    train_images,
    train_labels,
    test_images,
    test_labels,
    model.loss,
    damping=0.2,
    verbose=True,
    dtype=np.float64
)

In [6]:
influence_model.get_influence_on_loss(0, 0)

Calculating inverse HVP using Conjugate Gradient method:
Current error: 0.7839089510817655 , Relative error: 0.6329849239809454
Current error: 0.8542582485653691 , Relative error: 0.6897900474054476
Current error: 0.4018467745178628 , Relative error: 0.32448022142005906
Current error: 0.44385794356562075 , Relative error: 0.35840308530539816
Current error: 0.43379738011163904 , Relative error: 0.35027945693715945
Current error: 0.4096740294836777 , Relative error: 0.33080051459017623
Current error: 0.29862926979137516 , Relative error: 0.2411349243767754
Current error: 0.21130842212629908 , Relative error: 0.17062574082305337
Current error: 0.10796982625199027 , Relative error: 0.08718266600737336
Current error: 0.13073723728599432 , Relative error: 0.10556672441455796
Current error: 0.10193906684142102 , Relative error: 0.08231299360246115
Current error: 0.09489614197561537 , Relative error: 0.07662602542250412
Current error: 0.08306363917149046 , Relative error: 0.06707160474949395
C

-1.2443497044327205

In [7]:
influence_model.get_theta_relatif(0, 0)

-0.6052791994845195

In [8]:
influence_model.get_l_relatif(0, 0)

-1.0861122134592425

In [9]:
influence_model.get_new_parameters(0)

[<tf.Tensor: shape=(784, 10), dtype=float64, numpy=
 array([[-2.32880975e-13, -8.17070447e-14, -8.33336250e-14, ...,
          9.57189688e-13,  1.94641488e-12, -3.99829851e-12],
        [-2.80067446e-05, -1.61703146e-06, -6.70341766e-06, ...,
          5.63919557e-07, -1.42358302e-04, -5.09446173e-07],
        [ 2.21718047e-04,  1.18355512e-04, -1.48679482e-04, ...,
         -1.81714535e-05,  4.68826348e-05,  1.34745756e-05],
        ...,
        [-1.08012007e-02, -3.96097551e-03,  6.37298180e-03, ...,
          4.34476136e-03, -1.11750356e-02, -4.62698912e-03],
        [-2.60271868e-03, -7.66000138e-04, -6.67251045e-03, ...,
          9.21395606e-03,  2.21845453e-03, -1.03038333e-03],
        [ 1.79053260e-04,  4.47953423e-07, -2.64163802e-04, ...,
         -5.39193887e-04,  3.11970789e-05,  5.68377522e-05]])>,
 <tf.Tensor: shape=(10,), dtype=float64, numpy=
 array([ 0.06281225, -0.05549786, -0.05307192,  0.01316959, -0.32408354,
         0.75858732,  0.14867431, -0.04248875, -0.17874

In [10]:
lissa_influence_model = InfluenceModel(
    model,
    train_images,
    train_labels,
    test_images,
    test_labels,
    model.loss,
    method='lissa',
    scaling=0.01,
    verbose=True,
    dtype=np.float64
)

In [11]:
lissa_influence_model.get_influence_on_loss(0, 0)

Calculating inverse HVP using LiSSA method:
Sample 1 with depth 1000 - Current error: 0.008128780940861858 , Relative error: 0.656376725105295
Overall error: 0.008128780940861858 , Overall relative error: 0.656376725105295


-0.15813999588454486